name: daily_snapshot
description: "A new Flutter project."
publish_to: 'none'
version: 26.8.31+1

environment:
  sdk: ^3.13.1

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.2
  http: ^1.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/kma_regions.json
    - assets/images/app_icon.png
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
